// Code generated by mockgen. DO NOT EDIT.

package testdata

import (
	"context"
	"github.com/lvan100/gomock/gomock"
	"github.com/lvan100/gomock/mockgen/testdata/inner"
	"reflect"
)

type ServiceMockImpl struct {
	r *gomock.Manager
}

func NewServiceMockImpl(r *gomock.Manager) *ServiceMockImpl {
	return &ServiceMockImpl{r}
}

func (impl *ServiceMockImpl) Get(ctx context.Context, req *inner.Request, params map[string]string) (*Response, error) {
	t := reflect.TypeFor[ServiceMockImpl]()
	if ret, ok := gomock.Invoke(impl.r, t, "Get", ctx, req, params); ok {
		return gomock.Unbox2[*Response, error](ret)
	}
	panic("no mock code matched")
}

func (impl *ServiceMockImpl) MockGet() *gomock.Mocker32[context.Context, *inner.Request, map[string]string, *Response, error] {
	t := reflect.TypeFor[ServiceMockImpl]()
	return gomock.NewMocker32[context.Context, *inner.Request, map[string]string, *Response, error](impl.r, t, "Get")
}

type RepositoryMockImpl[T any] struct {
	r *gomock.Manager
}

func NewRepositoryMockImpl[T any](r *gomock.Manager) *RepositoryMockImpl[T] {
	return &RepositoryMockImpl[T]{r}
}

func (impl *RepositoryMockImpl[T]) Save(item T) error {
	t := reflect.TypeFor[RepositoryMockImpl[T]]()
	if ret, ok := gomock.Invoke(impl.r, t, "Save", item); ok {
		return gomock.Unbox1[error](ret)
	}
	panic("no mock code matched")
}

func (impl *RepositoryMockImpl[T]) MockSave() *gomock.Mocker11[T, error] {
	t := reflect.TypeFor[RepositoryMockImpl[T]]()
	return gomock.NewMocker11[T, error](impl.r, t, "Save")
}

func (impl *RepositoryMockImpl[T]) FindByID(id string) (T, error) {
	t := reflect.TypeFor[RepositoryMockImpl[T]]()
	if ret, ok := gomock.Invoke(impl.r, t, "FindByID", id); ok {
		return gomock.Unbox2[T, error](ret)
	}
	panic("no mock code matched")
}

func (impl *RepositoryMockImpl[T]) MockFindByID() *gomock.Mocker12[string, T, error] {
	t := reflect.TypeFor[RepositoryMockImpl[T]]()
	return gomock.NewMocker12[string, T, error](impl.r, t, "FindByID")
}

type RepositoryV2MockImpl[T ~int | ~uint] struct {
	r *gomock.Manager
}

func NewRepositoryV2MockImpl[T ~int | ~uint](r *gomock.Manager) *RepositoryV2MockImpl[T] {
	return &RepositoryV2MockImpl[T]{r}
}

func (impl *RepositoryV2MockImpl[T]) Save(item T) error {
	t := reflect.TypeFor[RepositoryV2MockImpl[T]]()
	if ret, ok := gomock.Invoke(impl.r, t, "Save", item); ok {
		return gomock.Unbox1[error](ret)
	}
	panic("no mock code matched")
}

func (impl *RepositoryV2MockImpl[T]) MockSave() *gomock.Mocker11[T, error] {
	t := reflect.TypeFor[RepositoryV2MockImpl[T]]()
	return gomock.NewMocker11[T, error](impl.r, t, "Save")
}

func (impl *RepositoryV2MockImpl[T]) FindByID(id string) (T, error) {
	t := reflect.TypeFor[RepositoryV2MockImpl[T]]()
	if ret, ok := gomock.Invoke(impl.r, t, "FindByID", id); ok {
		return gomock.Unbox2[T, error](ret)
	}
	panic("no mock code matched")
}

func (impl *RepositoryV2MockImpl[T]) MockFindByID() *gomock.Mocker12[string, T, error] {
	t := reflect.TypeFor[RepositoryV2MockImpl[T]]()
	return gomock.NewMocker12[string, T, error](impl.r, t, "FindByID")
}
